name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag chat-app:latest
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag chat-app:${{ github.run_number }}
      - name: Logs in to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASSWORD }}"
      - name: Publish to Docker Hub
        run: docker push chat-app:latest && docker push chat-app:${{ github.run_number }}
